- src/renderer/components/Button.tsx
- src/renderer/pages/Home.tsx
Mostly in response to what I wrote here: https://github.com/digidem/comapeo-desktop/pull/28#discussion_r1674442554, in case we prefer being less tied to MUI and want to unify the interface a bit across our custom components
> chore: use style instead of sx prop for Button

- src/renderer/Theme.ts
- src/renderer/colors.ts
- src/renderer/components/Text.tsx
- src/renderer/pages/Home.tsx
closes #17 
- Creates a shred Text component that accepts a prop kind, that returns either 'title' | 'body'  | 'subtitle'. If no kind if passed, it defaults to 'body'.
- accepts props for bold, italic, underline
- Can pass style to any of the text components but these will not override the bold, italic, underline
- Adds no text transform to the button as specified in the design docs (https://www.notion.so/digidem/Typography-a1600603854445ad82b8d67d4067be1a)
- Adds black to colors
> chore: Adds a text component 

- .github/workflows/lockfile.yml
Copies over the workflow we've set up in [core](https://github.com/digidem/comapeo-core/blob/main/.github/workflows/lockfile.yml). On pull requests, it runs a job for each of the following:
1. checking that the lockfile version doesn't change. this usually happens if someone uses an incompatible package manager version to manage dependencies, which we want to prevent
2. highlighting changes in dependencies that the PR introduces, if any, by writing a PR comment with a table
Introducing this will be helpful for avoiding any surprise updates and highlighting intended changes moving forward
Currently, this only introduces checks on the app-level lockfile and not the backend lockfile. Probably ideal to have it check both but haven't figured out the implementation for that yet.
> chore: add workflow for lockfile checks

- src/main/app.js
- src/main/ipc.js
- src/preload/main-window.js
- src/preload/runtime.d.ts
- src/renderer/src/hooks/mutations/file-system.ts
Related to #55
Sets up the mechanisms for initiating the selection of a file in the filesystem from the renderer side and retrieving the full path to the selected file. Having this will enable features such as importing a project config file or custom map file.
This PR introduces the following:
- IPC handler on the main window for summoning the open file dialog and returning the full path to the selected file (or `undefined` if no file is selected). Multi-file support was considered but we don't have an immediate need for it, so opted to refrain from including in this implementation.
- new renderer-available "runtime" method `selectFile(extensionFilters)` which sends the relevant IPC and waits for the result.
- mutation hook `useSelectProjectConfigFile()` which is unused in this PR, but …
> implement ipc for file selection

- src/main/app.js
- src/preload/main-window.js
- src/preload/runtime.d.ts
Updates `runtime.selectFile()` to return an object that contains the path and name of the selected file, as opposed to just the path. Informed by the needs of #55
> feat: update runtime.selectFile() to also return the file name

- src/renderer/src/components/button-link.tsx
- src/renderer/src/lib/navigation.ts
- src/renderer/src/routes/app/route.tsx
Forgot to implement as part of #133.
---
Preview:
> fix: disable navigation tabs when on device name settings page

- src/renderer/vite.config.js
Seems to just work without any extra configuration - nice!
Results when running `npm run vite:build` (aka `vite build src/renderer`):
Before:
```console
vite v7.0.5 building for production...
Generated route tree in 439ms
✓ 882 modules transformed.
../../dist/renderer/index.html                                                0.38 kB │ gzip:   0.26 kB
../../dist/renderer/assets/rubik-hebrew-wght-normal-aKm06Uuc.woff2            9.36 kB
../../dist/renderer/assets/rubik-cyrillic-ext-wght-normal-BjodpZir.woff2     12.39 kB
../../dist/renderer/assets/rubik-cyrillic-wght-normal-DveCct9I.woff2         15.11 kB
../../dist/renderer/assets/rubik-latin-ext-wght-normal-BmHZjB9M.woff2        19.51 kB
../../dist/renderer/assets/icons-sprite-C-J_6l-0.svg                         29.58 kB │ gzip:   8.96 …
```
> enable automatic code splitting

- src/main/app.js
- src/main/config-store.js
- src/main/ipc.js
- src/main/types/config-store.ts
- src/main/utils.js
- src/main/validation.js
- src/preload/runtime.ts
- src/renderer/src/lib/queries/app-settings.ts
Updates the config store schema to allow optional fields to be represented as missing keys in the config store JSON file. This makes updating the schema with new fields easier once it's out in the wild.
> fix: use a more flexible schema for config store

- src/renderer/src/lib/comapeo.ts
- src/renderer/src/routes/app/projects/$projectId/-displayed-data/list.tsx
- src/renderer/src/routes/app/projects/$projectId/-displayed-data/map.tsx
Follow-up to #172 because it turns out I don't know how categories are supposed to be matched 😅  The general approach is:
1. Use the document's `tags` field to determine if there's a matching preset
2. If (1) comes up empty, then use the document's `presetRef` to determine the matching preset.
For posterity, the reasoning as explained by Gregor:
> The reason for this is to support updating of the project presets / config: say a user has a preset for "bridge" and a question about what type of bridge it is, then in the next iteration of the config, the user creates a different preset for each type of bridge (matching on the bridge type tag), then we want existing data to match the correct bridge type preset, rather than use the "parent" generic bridge preset. This is how iDEditor implements …
> fix: update logic for category matching

- src/renderer/icons/material-error.svg
- src/renderer/src/components/category-icon.tsx
- src/renderer/src/components/error-boundary.tsx
- src/renderer/src/components/suspense-image.tsx
- src/renderer/src/images/icons-sprite.svg
- src/renderer/src/lib/comapeo.ts
- src/renderer/src/lib/image.ts
- src/renderer/src/routes/app/projects/$projectId/-displayed-data/list.tsx
- src/renderer/src/types/icons.generated.ts
Closes #162 
- At the moment, only displays photo attachments for observations.
- If attachments are displayed, only displays the first 3
- Implements an improvised error state for attachments or categories that fail to load. Probably needs some adjustments from design and user feedback.
---
Preview:
> feat: display observation attachments listed data

- docs/DEVELOPMENT.md
- forge.config.js
- src/main/index.js
Towards #97 
We have to tell dotenv the env file's location when it's not in the same directory as the process that starts the app.
Also uses this opportunity to simplify the build process a bit. No longer need a distinct `.env.production` file, as the plan is to generate a `.env` file in a github workflow step prior to building the app.
> fix: fix loading of env file in packaged app

- .github/workflows/hotfix-release.yml
- .nvmrc
- .tool-versions
- README.md
- package-lock.json
- package.json
Fell a bit behind the version that's used by Electron. Really should create a workflow check to catch this (will create an issue shortly)
> chore: update node version to 22.17.1

- messages/renderer/en.json
- src/main/app.js
- src/preload/main-window.js
- src/preload/runtime.ts
- src/renderer/src/routes/__root.tsx
Closes #209 
Might need some follow-ups based on what it looks like on Windows and Linux.
---
Preview:
- macOS:
- Ensuring overlays work as expected (e.g. error dialog, alerts):
> feat: implement custom title bar

- src/renderer/src/routes/__root.tsx
Follow-up to #211 . Didn't notice the warning that was being logged due to an incorrectly named css property.
> chore: fix warning about invalid css property name

- src/renderer/src/routes/app/projects/$projectId_/settings/info.tsx
- src/renderer/src/routes/app/settings/device-name.tsx
- src/renderer/src/routes/app/settings_/test-data.tsx
Was only an existing issue on the test data creation page, but updated other similar pages to avoid potential issues later on.
---
Preview:
- Before
- After:
> fix: ensure form field labels render underneath action buttons

- src/renderer/src/routes/app/settings_/test-data.tsx
Fixes a very minor issue of being able to navigate away from the test data creation page while the creation is still occurring. Usually more prone to issues when creating a large amount of data (e.g. 1000 observations).
> fix: disable navigation while test data is being created

- src/renderer/src/routes/onboarding/-shared/queries.ts
- src/renderer/src/routes/onboarding/project/index.tsx
- src/renderer/src/routes/onboarding/project/join.$inviteId/index.tsx
- src/renderer/src/routes/onboarding/route.tsx
#221 has enabled being able to actually test the project joining flow. Discovered quite a number of bugs as a result of being able to receive invites from mobile:
- fixes an issue with redirection logic after rejecting an invite
- fixes issue where invite cancellation does not trigger redirect
- addresses edge case of navigating to project invite page for an invite that cannot be responded to
- fixes issue where back button does not reject invite automatically
---
Preview (assumes that #221 is eventually merged):
https://github.com/user-attachments/assets/d7a4d343-844f-4bb8-aeaa-d0a29be9bd9e
> fix: various fixes for joining a project in onboarding

- messages/renderer/en.json
- src/renderer/src/components/error-dialog.tsx
- src/renderer/src/routes/app/settings_/test-data.tsx
Towards #161
Adds a toggle in the test creation page to enable creating a track that uses the observations created as its reference. We don't try to do anything super smart in terms of generating realistic location points for the track, and instead just use the observations' coordinates as the track's recorded locations.
---
Preview:
> feat: allow creation of track in test data creation page

- messages/renderer/en.json
- src/renderer/src/routes/app/projects/$projectId/-displayed-data/list.tsx
Fixes an issue where we the list item's title was the category name instead of just `Track`. Now it always displays `Track` despite the presence of an associated category
---
Preview:
> fix: fix title of track item in list

- src/renderer/src/routes/app/projects/$projectId/-displayed-data/list.tsx
The virtual list size calculation didn't account for the 1px added due to a bottom border on each item. This sometimes caused a vertical overflow within the list item (which thus shows the scrollbar unintentionally).
> fix: fix overflow within list item

- src/renderer/src/components/category-icon.tsx
Introduced this issue in #230 🤦 
---
Preview:
- Before:
- After:
> fix: fix rendering of category icon image when image fails to load

- messages/renderer/en.json
- src/main/app.js
- src/renderer/src/app.tsx
- src/renderer/src/components/app-title-bar.tsx
- src/renderer/src/index.css
- src/renderer/src/routes/__root.tsx
- On startup, shows the window when the 'ready-to-show` event fires, which reduces the visual flashing you see when opening the app. There's probably a slight cost to perceived startup time but it's negligible for now.
- Displays the title bar all the time. Used to only show after the initial loading state
> chore: app initilalization improvements

- messages/renderer/en.json
- src/renderer/src/components/generic-route-error-component.tsx
Updates the reload handling to follow tanstack router's [guidance](https://tanstack.com/router/latest/docs/framework/react/guide/data-loading#handling-errors-with-routeoptionserrorcomponent):
> If the error was the result of a route load, you should instead call router.invalidate(), which will coordinate both a router reload and an error boundary reset: 
Not all errors will be caused by route loading but at least those will be more idiomatically handled now.
> chore: update reload handler in generic route error component

- src/renderer/src/routes/onboarding/project/join.$inviteId/index.tsx
Closes #238 
Introduced this in #183 but didn't need to, as the original designs already accounted for surfacing errors in the screen.
> fix: do not show error dialog when invite response during onboarding fails

- forge.config.js
By convention, the executable name for the application on macOS is usually the same as the application name. However, I thought it would be okay for it to adhere to more conventional posix-naming i.e. lowercase + hyphen-separated. While this generally works, some applications will display the executable name instead of the application name, such as Raycast. On Finder, seems like it'll default to the name of the application directory found in the `Applications` folder, so it's not an issue for that at least. However, to potentially avoid similar cases with other tools, I think it's safer to just follow the convention instead of being more posix-friendly on macOS 😄 
---
Before:
After:
> fix: fix executable name for macOS

- src/renderer/src/routes/app/projects/$projectId_/invite/devices/$deviceId/send.tsx
Fixes an issue of flashing content if the attempt to send an invite fails
---
Preview:
- Before:
https://github.com/user-attachments/assets/92211228-5435-4c70-939a-ab8736a6df43
- After:
https://github.com/user-attachments/assets/a22bdb35-c379-472b-9b6d-5ba8636ab39b
> fix: prevent UI flashing when error occurs on sending invite

- .env.template
- docs/DEVELOPMENT.md
- forge.config.js
- src/main/app.js
- src/main/validation.js
- src/services/core.js
- src/shared/app.ts
Based on feedback from @rudokemper when setting up the development environment. Using a specific online style isn't necessary as core has its own defaults to use when setting it up if not configured.
---
Preview:
What the app looks like without configuring the variable:
> chore: make ONLINE_STYLE_URL env variable optional

- src/renderer/src/hooks/peers.ts
Pretty sure the issue lies in `@comapeo/ipc` or `rpc-reflector` where entry point being used for importing is pulling in a dep that relies on a node-only module, which vite cannot resolve without additional configuration. Changing the import to use the client-specific entry solves the problem, which is what we do throughout the renderer code, but forgot to do in this recently worked-on file. Probably should introduce some CI check to run the build to make sure that this doesn't happen again...
This is the original error that occurs when running `npm run vite:build`:
```console
error during build:
node_modules/ensure-error/index.js (1:8): "inspect" is not exported by "__vite-browser-external", imported by "node_modules/ensure-error/index.js".
file: …
```
> fix: fix build error when building renderer

- languages.json
The supported languages file didn't include the shortened language code for Mongolian and so it wasn't being detected as a language with translations available in the app.
---
Preview:
- Before:
- After:
> fix: make Mongolian a selectable language

- .github/parse-version/action.yml
- .github/workflows/build-rc.yml
- .github/workflows/check-pr-to-release.yml
- .github/workflows/ci.yml
- .github/workflows/create-builds.yml
- .github/workflows/hotfix-release.yml
- .github/workflows/lockfile.yml
- .github/workflows/post-release-check.yml
- .github/workflows/release.yml
- .github/workflows/scheduled-release.yml
Pinning is a precautionary measure against the security loophole of using version tags for actions (tags are mutable and thus can be pointed at bad commits if there's a compromise). More details here: https://docs.github.com/en/actions/reference/security/secure-use#using-third-party-actions
Used a combination of https://github.com/suzuki-shunsuke/pinact and https://github.com/azat-io/actions-up to do this. In most cases, can probably rely on the latter for doing upgrades.
> chore: update and pin GitHub actions

- src/renderer/src/components/icon.tsx
- src/renderer/src/components/zoom-to-data-map-control.tsx
- src/renderer/src/lib/icons.ts
Exporting it with a component from a file apparently doesn't play nicely with fast refresh: https://github.com/vitejs/vite-plugin-react/tree/main/packages/plugin-react#consistent-components-exports. Probably helpful to do this for isolation anyways.
> chore: extract getIconURL helper to lib

- messages/renderer/en.json
- src/renderer/icons/material-circle-filled.svg
- src/renderer/src/images/icons-sprite.svg
- src/renderer/src/routes/app/projects/$projectId_/exchange/index.tsx
- src/renderer/src/types/icons.generated.ts
Closes #176 
Shows under the following conditions:
1. the project has at least 1 active remote archive set up. no additional checks are made to know if it's actually online and ready to exchange.
2. Some wifi network is connected, regardless of internet access. Without some tedious pinging or additional changes to core, we can't directly check if a remote archive is online and ready to exchange.
---
Preview:
> feat: show remote archive indicator in exchange page

- scripts/generate-translated-languages-list.js
Follow-up to #269 . Tried to be fancy with it using import assertions which led to me forgetting that the result is a module object and not the JSON content itself. Going to back to good ol' readFileSync + json parse
> fix: fix script for generating translated languages

- src/renderer/src/routes/app/route.tsx
- src/renderer/src/routes/index.tsx
If the `activeProjectId` is missing on app start, we typically redirect the user to the onboarding flow, which is >99% of the cases that will happen. There's a <1% chance that the user has already created/joined a project but somehow the `activeProjectId` is missing, in which case it's preferable to prevent the user from going through the onboarding flow. This PR addresses this by redirecting the user to _some_ valid project. It's an edge case and the solution here feels like a short-term one. In the long-term, I think it'd be better to redirect the user to some project selection page where they can decide which project to enter (or even create/join a new one)
> fix: redirect user to an existing project when active project ID is missing

- src/renderer/src/routes/app/projects/$projectId/observations/$observationDocId/attachments/$driveId.$type.$variant.$name.tsx
Forgot to update the fallback behavior of the back button after copy-pasting from a different page.
> fix: fix fallback go-back behavior for observation attachment page

- .github/workflows/create-builds.yml
Aligns with what mobile has done recently. I added the variable for the repo that points to the newly updated URL that should be used, as opposed to the old one.
> chore: update builds workflow to use metrics URL from action vars
